CREATE DATABASE SMARTCHEFBD;
USE SMARTCHEFBD;

CREATE TABLE EMPRESA(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    USERNAME VARCHAR(65) NOT NULL,
    TELEFONE VARCHAR(18) NOT NULL,
    CNPJ VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    SENHA VARCHAR(256) NOT NULL,
    ATIVIDADE ENUM('ATIVO','INATIVO') NOT NULL
);

CREATE TABLE FUNCIONARIOS(
	ID INT NOT NULL PRIMARY KEY auto_increment,
    EMPRESA_ID INT NOT NULL,
    USERNAME VARCHAR(45) NOT NULL,
    SENHA VARCHAR(256) NOT NULL,
    FUNCAO ENUM('COZINHA','GARCOM','CAIXA','ADM'),
    TOKEN VARCHAR(256) NOT NULL,
    CHAVE INT NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE CASCADE
);

CREATE TABLE MESA(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    EMPRESA_ID INT NOT NULL,
    NUMERO INT NOT NULL,
    SENHA VARCHAR(256) NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE CASCADE
);

CREATE TABLE COMANDA(
	ID INT PRIMARY KEY auto_increment,
    MESA_ID INT NOT NULL,
    FUNCIONARIOS_ID INT NOT NULL,
    FOREIGN KEY (MESA_ID) REFERENCES MESA(ID) ON DELETE CASCADE,
    FOREIGN KEY (FUNCIONARIOS_ID) REFERENCES FUNCIONARIOS (ID) ON DELETE CASCADE
);

CREATE TABLE PEDIDO(
	ID INT PRIMARY KEY auto_increment,
    COMANDA_ID INT NOT NULL,
    ESTADO ENUM('PRONTO', 'EM PRODUCAO','EM ESPERA', 'CANCELADO') NOT NULL DEFAULT 'EM ESPERA',
    FOREIGN KEY (COMANDA_ID) REFERENCES COMANDA(ID) ON DELETE CASCADE
);

CREATE TABLE CARDAPIO(
	ID INT NOT NULL PRIMARY KEY auto_increment,
    EMPRESA_ID INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(50),
    INGREDIENTES VARCHAR(50) NOT NULL,
    PRECO DOUBLE NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE CASCADE
);

CREATE TABLE ITENS(
	ID INT PRIMARY KEY auto_increment,
    PEDIDO_ID INT NOT NULL,
    CARDAPIO_ID INT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID) ON DELETE CASCADE,
    FOREIGN KEY (CARDAPIO_ID) REFERENCES CARDAPIO(ID) ON DELETE CASCADE
);

CREATE TABLE HISTORICO(
	ID INT PRIMARY KEY auto_increment,
    EMPRESA_ID INT NOT NULL,
    DATA DATE NOT NULL,
    HISTORICO LONGTEXT NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE CASCADE
);